### ISSUE TITLE
Tugas 2

### ISSUE THREAD

**Issue by Alifias** [polinema-gui/tugas-2015-02-Alifias#1]
Maaf pak sebelumnya, mau bertanya bagaimana cara menyimpan perintah tugas baru ke dekstop Github ?

**Comment by dhanifudin** [comment]
mohon maaf dikarenakan adanya bugs pada Github Classroom sehingga template project tidak bisa diimport, template project sudah saya import secara manual. Silahkan baca dengan seksama file README.md yang ada pada repository.
